/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\CodeStandard\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-5eb9ba14",
    path: "/backend/API.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5eb9ba14").then(next)
    },
  },
  {
    name: "v-0ecfe13d",
    path: "/Update.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ecfe13d").then(next)
    },
  },
  {
    name: "v-6507acb8",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6507acb8").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-0e0fa910",
    path: "/backend/BaseCode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e0fa910").then(next)
    },
  },
  {
    name: "v-988350f8",
    path: "/backend/CodeCommit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-988350f8").then(next)
    },
  },
  {
    name: "v-f1bc4294",
    path: "/backend/Common.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f1bc4294").then(next)
    },
  },
  {
    name: "v-51715d14",
    path: "/backend/Enumerate.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51715d14").then(next)
    },
  },
  {
    name: "v-6196a196",
    path: "/backend/Dto.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6196a196").then(next)
    },
  },
  {
    name: "v-76b269b0",
    path: "/backend/Helper.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76b269b0").then(next)
    },
  },
  {
    name: "v-1bd5e598",
    path: "/backend/Module.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bd5e598").then(next)
    },
  },
  {
    name: "v-09759ad4",
    path: "/backend/Nuget.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09759ad4").then(next)
    },
  },
  {
    name: "v-24720b1b",
    path: "/backend/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24720b1b").then(next)
    },
  },
  {
    path: "/backend/index.html",
    redirect: "/backend/"
  },
  {
    name: "v-5d3419e0",
    path: "/backend/RabbitMq.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d3419e0").then(next)
    },
  },
  {
    name: "v-03576116",
    path: "/backend/Redis.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03576116").then(next)
    },
  },
  {
    name: "v-cbe0e694",
    path: "/backend/Table.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cbe0e694").then(next)
    },
  },
  {
    name: "v-246593f0",
    path: "/frontend/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-246593f0").then(next)
    },
  },
  {
    name: "v-92d42b60",
    path: "/frontend/HTML.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-92d42b60").then(next)
    },
  },
  {
    name: "v-bcecc720",
    path: "/frontend/Images.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bcecc720").then(next)
    },
  },
  {
    name: "v-82b3eb60",
    path: "/frontend/Name.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82b3eb60").then(next)
    },
  },
  {
    name: "v-201f25b0",
    path: "/frontend/VSCode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-201f25b0").then(next)
    },
  },
  {
    name: "v-375190db",
    path: "/frontend/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-375190db").then(next)
    },
  },
  {
    path: "/frontend/index.html",
    redirect: "/frontend/"
  },
  {
    name: "v-038216aa",
    path: "/frontend/Vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-038216aa").then(next)
    },
  },
  {
    name: "v-915208e0",
    path: "/frontend/JavaScript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-915208e0").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]