/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "开发手册",
  "description": "团队开发规范建议",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Api 接口规范",
      "frontmatter": {
        "title": "Api 接口规范"
      },
      "regularPath": "/backend/API.html",
      "relativePath": "backend/API.md",
      "key": "v-5eb9ba14",
      "path": "/backend/API.html",
      "headers": [
        {
          "level": 2,
          "title": "接口命名规范",
          "slug": "接口命名规范"
        },
        {
          "level": 2,
          "title": "EF 使用规范",
          "slug": "ef-使用规范"
        },
        {
          "level": 2,
          "title": "其他规范",
          "slug": "其他规范"
        }
      ]
    },
    {
      "title": "1.2.2",
      "frontmatter": {},
      "regularPath": "/Update.html",
      "relativePath": "Update.md",
      "key": "v-0ecfe13d",
      "path": "/Update.html",
      "headers": [
        {
          "level": 3,
          "title": "1.2.2",
          "slug": "_1-2-2"
        },
        {
          "level": 3,
          "title": "1.2.1",
          "slug": "_1-2-1"
        },
        {
          "level": 3,
          "title": "1.2.0",
          "slug": "_1-2-0"
        },
        {
          "level": 3,
          "title": "1.1.0",
          "slug": "_1-1-0"
        },
        {
          "level": 3,
          "title": "1.0.0",
          "slug": "_1-0-0"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/favicon.ico",
        "actionText": "立即开始 →",
        "actionLink": "/frontend/",
        "features": [
          {
            "title": "内容",
            "details": "包含前后端各类型规范、建议内容"
          },
          {
            "title": "用途",
            "details": "用于日常业务需求以及统一开发目的"
          }
        ],
        "footer": "© 2020 东华机械有限公司"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-6507acb8",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "最近更新",
          "slug": "最近更新"
        },
        {
          "level": 3,
          "title": "1.2.2",
          "slug": "_1-2-2"
        }
      ]
    },
    {
      "title": "基本代码规范",
      "frontmatter": {
        "title": "基本代码规范"
      },
      "regularPath": "/backend/BaseCode.html",
      "relativePath": "backend/BaseCode.md",
      "key": "v-0e0fa910",
      "path": "/backend/BaseCode.html",
      "headers": [
        {
          "level": 2,
          "title": "代码格式",
          "slug": "代码格式"
        },
        {
          "level": 3,
          "title": "花括号",
          "slug": "花括号"
        },
        {
          "level": 3,
          "title": "换行",
          "slug": "换行"
        },
        {
          "level": 3,
          "title": "空行",
          "slug": "空行"
        },
        {
          "level": 3,
          "title": "语句结构",
          "slug": "语句结构"
        },
        {
          "level": 3,
          "title": "Using 排序",
          "slug": "using-排序"
        },
        {
          "level": 3,
          "title": "文件命名",
          "slug": "文件命名"
        },
        {
          "level": 3,
          "title": "注释",
          "slug": "注释"
        }
      ]
    },
    {
      "title": "代码提交发布规范",
      "frontmatter": {
        "title": "代码提交发布规范"
      },
      "regularPath": "/backend/CodeCommit.html",
      "relativePath": "backend/CodeCommit.md",
      "key": "v-988350f8",
      "path": "/backend/CodeCommit.html",
      "headers": [
        {
          "level": 2,
          "title": "代码提交",
          "slug": "代码提交"
        }
      ]
    },
    {
      "title": "iSee 公共字段",
      "frontmatter": {
        "title": "iSee 公共字段"
      },
      "regularPath": "/backend/Common.html",
      "relativePath": "backend/Common.md",
      "key": "v-f1bc4294",
      "path": "/backend/Common.html"
    },
    {
      "title": "枚举命名规范",
      "frontmatter": {
        "title": "枚举命名规范"
      },
      "regularPath": "/backend/Enumerate.html",
      "relativePath": "backend/Enumerate.md",
      "key": "v-51715d14",
      "path": "/backend/Enumerate.html",
      "headers": [
        {
          "level": 2,
          "title": "枚举建立原则",
          "slug": "枚举建立原则"
        },
        {
          "level": 2,
          "title": "枚举命名规范",
          "slug": "枚举命名规范-2"
        }
      ]
    },
    {
      "title": "实体和 Dto",
      "frontmatter": {
        "title": "实体和 Dto"
      },
      "regularPath": "/backend/Dto.html",
      "relativePath": "backend/Dto.md",
      "key": "v-6196a196",
      "path": "/backend/Dto.html",
      "headers": [
        {
          "level": 2,
          "title": "实体命名规范",
          "slug": "实体命名规范"
        },
        {
          "level": 2,
          "title": "实体添加特性",
          "slug": "实体添加特性"
        },
        {
          "level": 2,
          "title": "实体继承接口",
          "slug": "实体继承接口"
        },
        {
          "level": 2,
          "title": "Dto 命名规范",
          "slug": "dto-命名规范"
        }
      ]
    },
    {
      "title": "工具类 Helper 规范",
      "frontmatter": {
        "title": "工具类 Helper 规范"
      },
      "regularPath": "/backend/Helper.html",
      "relativePath": "backend/Helper.md",
      "key": "v-76b269b0",
      "path": "/backend/Helper.html"
    },
    {
      "title": "模块规范",
      "frontmatter": {
        "title": "模块规范"
      },
      "regularPath": "/backend/Module.html",
      "relativePath": "backend/Module.md",
      "key": "v-1bd5e598",
      "path": "/backend/Module.html",
      "headers": [
        {
          "level": 2,
          "title": "模块命名规范",
          "slug": "模块命名规范"
        },
        {
          "level": 2,
          "title": "模块文件夹结构",
          "slug": "模块文件夹结构"
        },
        {
          "level": 2,
          "title": "模块依赖关系",
          "slug": "模块依赖关系"
        },
        {
          "level": 2,
          "title": "模块添加步骤",
          "slug": "模块添加步骤"
        },
        {
          "level": 2,
          "title": "添加实体与 Dto 映射",
          "slug": "添加实体与-dto-映射"
        }
      ]
    },
    {
      "title": "Nuget 包管理规范",
      "frontmatter": {
        "title": "Nuget 包管理规范"
      },
      "regularPath": "/backend/Nuget.html",
      "relativePath": "backend/Nuget.md",
      "key": "v-09759ad4",
      "path": "/backend/Nuget.html"
    },
    {
      "title": "介绍",
      "frontmatter": {
        "title": "介绍",
        "sidebarDepth": 1
      },
      "regularPath": "/backend/",
      "relativePath": "backend/README.md",
      "key": "v-24720b1b",
      "path": "/backend/"
    },
    {
      "title": "RabbitMq 使用规范",
      "frontmatter": {
        "title": "RabbitMq 使用规范"
      },
      "regularPath": "/backend/RabbitMq.html",
      "relativePath": "backend/RabbitMq.md",
      "key": "v-5d3419e0",
      "path": "/backend/RabbitMq.html"
    },
    {
      "title": "Redis 使用规范",
      "frontmatter": {
        "title": "Redis 使用规范"
      },
      "regularPath": "/backend/Redis.html",
      "relativePath": "backend/Redis.md",
      "key": "v-03576116",
      "path": "/backend/Redis.html",
      "headers": [
        {
          "level": 2,
          "title": "Redis 使用原则",
          "slug": "redis-使用原则"
        },
        {
          "level": 2,
          "title": "RedisKey 命名规范",
          "slug": "rediskey-命名规范"
        }
      ]
    },
    {
      "title": "表索引及分区表",
      "frontmatter": {
        "title": "表索引及分区表"
      },
      "regularPath": "/backend/Table.html",
      "relativePath": "backend/Table.md",
      "key": "v-cbe0e694",
      "path": "/backend/Table.html",
      "headers": [
        {
          "level": 2,
          "title": "索引规范",
          "slug": "索引规范"
        },
        {
          "level": 3,
          "title": "索引名称",
          "slug": "索引名称"
        },
        {
          "level": 3,
          "title": "需要建立索引的情况",
          "slug": "需要建立索引的情况"
        },
        {
          "level": 3,
          "title": "索引使用查询规范",
          "slug": "索引使用查询规范"
        },
        {
          "level": 2,
          "title": "分区表规范",
          "slug": "分区表规范"
        }
      ]
    },
    {
      "title": "CSS",
      "frontmatter": {
        "title": "CSS"
      },
      "regularPath": "/frontend/CSS.html",
      "relativePath": "frontend/CSS.md",
      "key": "v-246593f0",
      "path": "/frontend/CSS.html",
      "headers": [
        {
          "level": 2,
          "title": "代码风格",
          "slug": "代码风格"
        },
        {
          "level": 3,
          "title": "通用",
          "slug": "通用"
        },
        {
          "level": 3,
          "title": "空格",
          "slug": "空格"
        },
        {
          "level": 3,
          "title": "选择器",
          "slug": "选择器"
        },
        {
          "level": 3,
          "title": "属性缩写",
          "slug": "属性缩写"
        },
        {
          "level": 3,
          "title": "值与单位",
          "slug": "值与单位"
        },
        {
          "level": 3,
          "title": "属性书写顺序",
          "slug": "属性书写顺序"
        },
        {
          "level": 3,
          "title": "!important",
          "slug": "important"
        },
        {
          "level": 3,
          "title": "z-index",
          "slug": "z-index"
        },
        {
          "level": 3,
          "title": "私有前缀",
          "slug": "私有前缀"
        },
        {
          "level": 3,
          "title": "文件信息注释",
          "slug": "文件信息注释"
        },
        {
          "level": 3,
          "title": "媒介查询",
          "slug": "媒介查询"
        }
      ]
    },
    {
      "title": "HTML",
      "frontmatter": {
        "title": "HTML"
      },
      "regularPath": "/frontend/HTML.html",
      "relativePath": "frontend/HTML.md",
      "key": "v-92d42b60",
      "path": "/frontend/HTML.html",
      "headers": [
        {
          "level": 2,
          "title": "代码规范",
          "slug": "代码规范"
        },
        {
          "level": 3,
          "title": "通用",
          "slug": "通用"
        },
        {
          "level": 3,
          "title": "书写风格",
          "slug": "书写风格"
        },
        {
          "level": 3,
          "title": "注释",
          "slug": "注释"
        }
      ]
    },
    {
      "title": "图片规范",
      "frontmatter": {
        "title": "图片规范"
      },
      "regularPath": "/frontend/Images.html",
      "relativePath": "frontend/Images.md",
      "key": "v-bcecc720",
      "path": "/frontend/Images.html",
      "headers": [
        {
          "level": 3,
          "title": "内容图",
          "slug": "内容图"
        },
        {
          "level": 3,
          "title": "背景图",
          "slug": "背景图"
        },
        {
          "level": 3,
          "title": "SVG",
          "slug": "svg"
        }
      ]
    },
    {
      "title": "命名规范",
      "frontmatter": {
        "title": "命名规范"
      },
      "regularPath": "/frontend/Name.html",
      "relativePath": "frontend/Name.md",
      "key": "v-82b3eb60",
      "path": "/frontend/Name.html",
      "headers": [
        {
          "level": 2,
          "title": "className 命名",
          "slug": "classname-命名"
        },
        {
          "level": 2,
          "title": "ID 命名",
          "slug": "id-命名"
        },
        {
          "level": 2,
          "title": "文件命名",
          "slug": "文件命名"
        },
        {
          "level": 2,
          "title": "组件命名",
          "slug": "组件命名"
        }
      ]
    },
    {
      "title": "VSCode",
      "frontmatter": {
        "title": "VSCode"
      },
      "regularPath": "/frontend/VSCode.html",
      "relativePath": "frontend/VSCode.md",
      "key": "v-201f25b0",
      "path": "/frontend/VSCode.html",
      "headers": [
        {
          "level": 2,
          "title": "配置换行",
          "slug": "配置换行"
        },
        {
          "level": 2,
          "title": "安装 Prettier",
          "slug": "安装-prettier"
        },
        {
          "level": 2,
          "title": "安装 Vetur",
          "slug": "安装-vetur"
        },
        {
          "level": 2,
          "title": "配置 ESLint",
          "slug": "配置-eslint"
        },
        {
          "level": 2,
          "title": "其它插件",
          "slug": "其它插件"
        }
      ]
    },
    {
      "title": "介绍",
      "frontmatter": {
        "title": "介绍",
        "sidebarDepth": 1
      },
      "regularPath": "/frontend/",
      "relativePath": "frontend/README.md",
      "key": "v-375190db",
      "path": "/frontend/"
    },
    {
      "title": "Vue",
      "frontmatter": {
        "title": "Vue"
      },
      "regularPath": "/frontend/Vue.html",
      "relativePath": "frontend/Vue.md",
      "key": "v-038216aa",
      "path": "/frontend/Vue.html",
      "headers": [
        {
          "level": 2,
          "title": "风格指南",
          "slug": "风格指南"
        },
        {
          "level": 2,
          "title": "深度选择器",
          "slug": "深度选择器"
        },
        {
          "level": 2,
          "title": "Views",
          "slug": "views"
        }
      ]
    },
    {
      "title": "JavaScript",
      "frontmatter": {
        "title": "JavaScript"
      },
      "regularPath": "/frontend/JavaScript.html",
      "relativePath": "frontend/JavaScript.md",
      "key": "v-915208e0",
      "path": "/frontend/JavaScript.html",
      "headers": [
        {
          "level": 2,
          "title": "代码风格",
          "slug": "代码风格"
        },
        {
          "level": 3,
          "title": "换行",
          "slug": "换行"
        },
        {
          "level": 3,
          "title": "变量声明",
          "slug": "变量声明"
        },
        {
          "level": 3,
          "title": "命名",
          "slug": "命名"
        },
        {
          "level": 2,
          "title": "语言特性",
          "slug": "语言特性"
        },
        {
          "level": 3,
          "title": "变量",
          "slug": "变量"
        },
        {
          "level": 3,
          "title": "条件",
          "slug": "条件"
        },
        {
          "level": 3,
          "title": "循环",
          "slug": "循环"
        },
        {
          "level": 3,
          "title": "类型",
          "slug": "类型"
        },
        {
          "level": 3,
          "title": "对象",
          "slug": "对象"
        },
        {
          "level": 3,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 3,
          "title": "解构赋值",
          "slug": "解构赋值"
        },
        {
          "level": 3,
          "title": "字符串",
          "slug": "字符串"
        },
        {
          "level": 3,
          "title": "函数",
          "slug": "函数"
        },
        {
          "level": 3,
          "title": "原型",
          "slug": "原型"
        },
        {
          "level": 3,
          "title": "模块",
          "slug": "模块"
        },
        {
          "level": 3,
          "title": "默认数据",
          "slug": "默认数据"
        },
        {
          "level": 3,
          "title": "分号 / 引号",
          "slug": "分号-引号"
        },
        {
          "level": 2,
          "title": "ESNext 建议",
          "slug": "esnext-建议"
        },
        {
          "level": 2,
          "title": "注释",
          "slug": "注释"
        },
        {
          "level": 3,
          "title": "单行注释",
          "slug": "单行注释"
        },
        {
          "level": 3,
          "title": "多行注释",
          "slug": "多行注释"
        },
        {
          "level": 3,
          "title": "函数注释",
          "slug": "函数注释"
        },
        {
          "level": 3,
          "title": "扩展阅读",
          "slug": "扩展阅读"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "nav": [
      {
        "text": "更新日志",
        "link": "/Update"
      },
      {
        "text": "iSee 导航",
        "link": "http://192.168.110.10/"
      }
    ],
    "sidebarDepth": 2,
    "sidebar": [
      {
        "title": "前端",
        "collapsable": false,
        "children": [
          "frontend/",
          "frontend/HTML",
          "frontend/CSS",
          "frontend/JavaScript",
          "frontend/Vue",
          "frontend/Name",
          "frontend/Images",
          "frontend/VSCode"
        ]
      },
      {
        "title": "后端",
        "collapsable": false,
        "children": [
          "backend/BaseCode",
          "backend/Dto",
          "backend/Table",
          "backend/Common",
          "backend/API",
          "backend/Module",
          "backend/Nuget",
          "backend/Enumerate",
          "backend/Redis",
          "backend/RabbitMq",
          "backend/Helper",
          "backend/CodeCommit"
        ]
      }
    ]
  }
}